Sesh
GameW1zard/Group-5-Project-2 pull request #11
Opened 2023-05-17 02:19 UTC by Chartok

2023-05-17 02:24 UTC, GameW1zard requested changes

2023-05-17 02:24 UTC, GameW1zard commented on .env.example
password left in file

2023-05-17 06:19 UTC, Chartok commented on .env.example
> -DB_USER='root'
Took care of the pw

2023-05-18 03:24 UTC, GameW1zard approved these changes

2023-05-18 03:27 UTC, merged